export const alertType={
    SUCCESS:"ALERT_SUCCESS",
    ERROR:"ALERT_ERROR",
    CLEAR:"ALERT_CLEAR"
}
export const userType={
    REGISTER_REQUEST:"USER_REGISTER_REQUEST",
    REGISTER_SUCCESS:"USER_REGISTER_SUCCESS",
    REGISTER_FAILURE:"USER_REGISTER_FAILURE",

    LOGIN_REQUEST:"USER_LOGIN_REQUEST",
    LOGIN_SUCCESS:"USER_LOGIN_SUCCESS",
    LOGIN_FAILURE:"USER_LOGIN_FAILURE",

    LOGOUT:"USERS_LOGOUT",

    GET_ALL_REQUEST:"USERS_GET_ALL_REQUEST",
    GET_ALL_SUCCESS:"USERS_GET_ALL_SUCCESS",
    GET_ALL_FAILURE:"USERS_GET_ALL_FAILURE",

    DELETE_REQUEST:"USER_DELETE_REQUEST",
    DELETE_SUCCESS:"USER_DELETE_SUCCESS",
    DELETE_FAILURE:"USER_DELETE_FAILURE"
}